name = "s-bandwidth-graph-weightings"
uuid = "76963964-dda3-48b0-b31a-1cf4a5e32131"
keywords = [
    "linear algebra",
    "graph theory",
    "spectral graph theory",
    "quantum computing",
    "linear programming",
]
license = "MIT"
authors = ["Luis M. B. Varona <lm.varona@outlook.com>"]
description = "Computational indications that no positive edge weighting can reduce the S-bandwidth of a graph"
maintainers = ["Luis M. B. Varona <lm.varona@outlook.com>"]
readme = "README.md"
repository = "https://github.com/Luis-Varona/s-bandwidth-graph-weightings"
version = "1.0.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MatrixBandwidth = "075aa41b-24fd-4573-b25f-92cae432c0f8"
SDiagonalizability = "addecc1e-711d-4b49-877e-3152f1574f63"

[compat]
Combinatorics = "1.0"
ElasticArrays = "1.2"
LinearAlgebra = "1.10"
MAT = "0.10.6"
MatrixBandwidth = "0.1 - 0.2"
SDiagonalizability = "0.1"
julia = "1.10"
